name: Test
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - uses: kikyous/template-action@v2.0.0
        id: template-path
        with:
          template-path: ".github/workflows/test.ejs.md"
          post-run: |
            curl -s '${{ secrets.WECHAT_WORK_WEBHOOK_URL }}' \
              -H 'Content-Type: application/json' \
              -d '{
                "msgtype": "markdown",
                "markdown": { "content": <%- JSON.stringify(output) %> }
              }'


      - name: Get the render output
        run: echo "${{ steps.template-path.outputs.content }}"

      - uses: kikyous/template-action@v2.0.0
        id: template
        with:
          template: "<%- JSON.stringify(context, undefined, 2) %>"
          post-run: echo "<%- output %>"

