name: Test
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kikyous/template-action@v0.0.3
        id: template
        with:
          template: "{{=JSON.stringify(it)}}"

      - name: Get the render output
        run: echo "${{ steps.template.outputs.content }}"
