name: Test
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - uses: kikyous/template-action@v2.0.0
        id: template-path
        with:
          template-path: ".github/workflows/test.ejs.md"
          post-run: echo "<%= output %>"

      - name: Get the render output
        run: echo "${{ steps.template-path.outputs.content }}"

      - uses: kikyous/template-action@v2.0.0
        id: template
        with:
          template: "<%= JSON.stringify(it.context, undefined, 2) %>"
          post-run: echo "<%= output %>"

